# Generated by Django 5.2.7 on 2025-10-22 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DurationRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('minutes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('membership_price', models.IntegerField()),
                ('general_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='durationrate', to='control.store')),
            ],
        ),
        migrations.CreateModel(
            name='DailyStoreSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paypay_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dailystoresales', to='control.store')),
            ],
        ),
    ]
