# Generated by Django 5.2.7 on 2025-11-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='pricing_logic',
            field=models.CharField(choices=[('duration_rate', 'Duration Rate (Default)')], db_index=True, default='duration_rate', max_length=50),
        ),
    ]
