# Generated by Django 5.2.7 on 2025-11-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='expired_days',
            field=models.IntegerField(default=90),
        ),
    ]
