# Generated by Django 5.2.7 on 2025-11-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_store_expired_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='expired_days',
            new_name='membership_validity_period',
        ),
    ]
