# Generated by Django 5.2.7 on 2025-11-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='register_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
