# Generated by Django 5.2.7 on 2025-11-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
        ('customer', '0002_membership_address_membership_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='address',
            new_name='first_name_kana',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='email',
        ),
        migrations.AddField(
            model_name='membership',
            name='last_name_kana',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('store', 'phone_number'), name='unique_store_phone_number'),
        ),
    ]
